hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "6b0382b16279f26ff69014300541967a356a666eb0b91b422f6862f6b7dad17e"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "fbad3ce2bcab1b8a73a541000100dc5ed3323bcf571e4e2a4a3c28db5c520509"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "b494eb2872c5eb3c498e147be24a62e2c62485e375b9b99c15ae0faf8f9dd2ca"
metafile = true

[[files]]
file = "mods/antighost.pw.toml"
hash = "242e18d68cb8d218df43e713e97239631f8612384789068659c4898cfa49fcef"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "4d571d5ebe245ffb62a0df83e81d1c03670807d3528650d6dd9c983bd26ae860"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a714c0d9b19e623a1ed9e130c446174a7eda24a7146afeb4e2d82498f8c8ea5c"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "fa7eed08ecb81a2cc3ec4f9cc5387874936f2496a5739ec71d263a6f26a45c34"
metafile = true

[[files]]
file = "mods/biomesyougo.pw.toml"
hash = "f9daa7f4a22030249d4ba643df59c7fc4e49b2cdaf6fc4adb9df70a8827d3f6e"
metafile = true

[[files]]
file = "mods/boosted-brightness.pw.toml"
hash = "5d7d1c6d7d68f972478ccfd02820f18f3db5e761ecf5965d9e1e151a8a75938a"
metafile = true

[[files]]
file = "mods/brrp.pw.toml"
hash = "6f33cb2d9b193bdc314bd10c59489346ab688899574077a81548e98e0d361334"
metafile = true

[[files]]
file = "mods/cake-chomps.pw.toml"
hash = "a6dd7c4d9101f127c0a0b5ce1154dcf8d28cc6822d35b62c0be3c052852b8e92"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "1d5ff51cdf133abc091eda828043e7f4472bba1faea1faacc41bb50ca8315b28"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "881ddb59302c7dd6762c06c10f6d858b74749c8aea781d02339efd482fe10a9f"
metafile = true

[[files]]
file = "mods/cc-restitched.pw.toml"
hash = "6e8faa4779dca8bafd4cc91cad8f7fe425f6d3d08511463466c6c13b8ffa55dd"
metafile = true

[[files]]
file = "mods/cccbridge.pw.toml"
hash = "72a444170f6963bc57c323f98d01d22bdcd400be26a2bfd1d3d02ea34ad096de"
metafile = true

[[files]]
file = "mods/cem.pw.toml"
hash = "7f63923d2240d002b0d113eec8a2fea4869837c09386faed9e1a4d096552d594"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "0da3b33d0d62fcaf24835fb432b8dd9be02e82897cd43fddc38fa81106203d37"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "213cad77d46ff46fe20780b01856cb1a8812747e9c3564203669bf3905e646e2"
metafile = true

[[files]]
file = "mods/colormatic.pw.toml"
hash = "c49d1423a5f2563335fd5719862a861c8ae2c9cbc46598e767c3e2fe1042ecae"
metafile = true

[[files]]
file = "mods/completeconfig.pw.toml"
hash = "a206bc693d41eb72f431abfc5d4556f9e9bf7f0bb6237224b750df85aeddd434"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "3cbe3d523b39667928fcc34f71651b0e581e5c541dd5ecf17228464770466bc5"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "9322278362644f81f8cc456b622d0b761eaf2677abbaca5db1952b23098a33bb"
metafile = true

[[files]]
file = "mods/create-chunkloading.pw.toml"
hash = "d9c7722a164bebefdd8bb8945c37f6f33db30fa68506e4dea6a8f3fdaa2a0b97"
metafile = true

[[files]]
file = "mods/create-crystal-clear-fabric.pw.toml"
hash = "790d09e1bee44adf6f4867d2c63a4626c96c5b8eec0b9f8ea2a14f8465434f02"
metafile = true

[[files]]
file = "mods/create-deco-fabric.pw.toml"
hash = "3e2ed46e1811a2452f21cb75dfe5952b32e13e5845ac707e6ff199a14b58a6be"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "b1aa83bed8ef891dff38190701b48f6dd70085c26159f9316334bbe85b935ead"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "8260c756c1da49c5c97ef81d1442018979d6979aac0e37a79c864a680e15cf5d"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
hash = "bc53f7664438ab4e84ac236950bc75a61b2945e32f51777c358187a9bf581dd3"
metafile = true

[[files]]
file = "mods/cull-less-leaves.pw.toml"
hash = "c06e098c6d6eda6da4492e4a8dff1796e6081bbd30f487ffb89e1ed3c485e805"
metafile = true

[[files]]
file = "mods/dcch.pw.toml"
hash = "0d1b70e6b6851d0b765fc94d5c6f9201eaee8201bacc2d2604db15b2ab2b3364"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "783c0415795fc4bea6d85315aac54d3a3f2770fcd02d66dad1f626b311f8bf4f"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "0ada4f3b91ee6a4cd40c8e9bcb69a3d59c24ff3940762efca9253b269af1eb25"
metafile = true

[[files]]
file = "mods/easyauth.pw.toml"
hash = "f2b5fecdf40015075b0c6feebdf54685e3dfedb00d68fa056d8a72b6585a3c2e"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "81a389a5035dc0852ce12c796f1d667bb4715b1d6ffde16433bf80f02e3796bc"
metafile = true

[[files]]
file = "mods/emoji-type.pw.toml"
hash = "7a6a192d8b94f9363b7a741b6758316437c56598ee0156c479949e71b6c80f7c"
metafile = true

[[files]]
file = "mods/emotecraft.pw.toml"
hash = "d730fc095167a665e54d8ce5a636f766cdd3cda52ed62168d48ca9826f676343"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "bf886d03a194a4036f02afe690cb21ca346fff20f4193355994ec97f046a8809"
metafile = true

[[files]]
file = "mods/extra-thicc-packets.pw.toml"
hash = "4abe2f719878f0ac44b288cd2804da49d487b9d5481fd0217bd396284bf43725"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
hash = "2ecf8a35b7a0f6f00245fc95bc1d15f40ddcbb3c31794e2447911099a326ff9c"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
hash = "1ef7f8449365aa7f1185447ca46bc1c742e3d766c9dffb90b90447daed049042"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "46a497398e476b0bbac4a1c9816da987be2a9afc2e62011d584963beef0ba45e"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "98da553a1ba2d41bfce3585198641c2d927c702d5403ebec82402ae51ddf707f"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "0497a92235c08a5ace339102c702d17e529c0770b3a340bdecebe321e3213888"
metafile = true

[[files]]
file = "mods/gravestones.pw.toml"
hash = "58ec51afc2354d65aeb2f9e068d8467fb2d3c13a3e751325385a59d5d493930f"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "8847ebb401a474d65b2ffd00a226356e94791db3f5cf98505beb227e74298884"
metafile = true

[[files]]
file = "mods/htm.pw.toml"
hash = "561eee5ab7553061d4489cebb24b9c9f7249b716dbedc6c0e5428cc2f039b0a1"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "7d36d5a19b32363dc9795b0f4610705e332c0100169b2ec4a54654b0923ba89f"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e8168531c092676d47cac3657bfc525f096f11ff5372ce6e322ad57778b81635"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "2355898e55539353e3fe43057c1c2880e02ceb6b64c8f5d1e0bc2a660635c323"
metafile = true

[[files]]
file = "mods/item-model-fix.pw.toml"
hash = "e6895b572857d6381b9c5c8d153eb6606b3cd2755feec53ff3905d025656a124"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "86bdf3e7c87946fad718883449651e7606fba0d0fa173eb32b3d985e2a2cd8d5"
metafile = true

[[files]]
file = "mods/lambdabettergrass.pw.toml"
hash = "507abebf9ae5282c92a1c799ed9666e23f0605190633c16e086b1c9e17ad4465"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9b628c73b749c901f12ba08b8304c161801903b1dd3fdbb6d4b93a9d42d25afa"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "e7e06878a40e4733a45b06aba4e1adaf09905485268e9c19e75a6ed9c0f86490"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
hash = "cbd6b97dfc49090b18480f43eeef4401144006ed406110f32fb1126d47a21f11"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "28b3808ae3e3e5bcc8f2a6dfe40c539a2e55afd3687e41c681dc408021e395ef"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "a4a461e73eb037dd5b5f3015a9a53d947c4533535b98f072f4ea96e90e9d68e4"
metafile = true

[[files]]
file = "mods/macaws-bridges-oh-the-biomes-youll-go.pw.toml"
hash = "a603b8ee93008d7100f8cfec635498f3c585e1edf10f2c05b237eaf0f75bce70"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "46abacb059a2af9fe270f2be6c714ac7d5eeee71b4a9fa2f20ac047438a12cab"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "9bd46b5d5a2346aaa9da4cef1b5c5683d8621e8d1d89d2634e51614f3a7ca093"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "b16dd6d03444954164f412bdbbf33c23e88a28daf83fa4628027c6b3e167107a"
metafile = true

[[files]]
file = "mods/macaws-fences-oh-the-biomes-youll-go.pw.toml"
hash = "ff1a70511338c17c698d4e0b2b5980e0576a88385ed1cde03d7fbfd491b2b688"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "f4fdb82265f6fcff7dafcff59bd579ac335b37b16808e094e940d819233cfe77"
metafile = true

[[files]]
file = "mods/macaws-paintings.pw.toml"
hash = "f2b787b718283a97f997fb0138a04a790bedf65f6d7edfd30728da9dda692e5a"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "867d03dd010e40e9391cd6a9a314a0accf77a3798510a4bcc9391269f451e6b6"
metafile = true

[[files]]
file = "mods/macaws-roofs-oh-the-biomes-youll-go.pw.toml"
hash = "ec182bf912a7a9c8c79022b0410459ba678cf55ac0db391255f4f37805a90cf3"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "e5fd62acfa586a4066ba2ba88b3de175ebfca4f9aea9beb7beb63a0076c88301"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "eb4071fdeee678fce838bc85391981b0d66a558a30ab15b12890e6d8d842cda7"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "5ee8fe6018c7ad0fba0a3aa434aae95c7c3aee860f14262276459c4cfbbde17c"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "2f1393d78824d3e665be954e339affed26d8482d227aa3f13d6ca5d577469f8b"
metafile = true

[[files]]
file = "mods/mixin-conflict-helper.pw.toml"
hash = "c7388b6ebb78040be98251fb064a009f3d7574133e15d2844e3fadf2929b2980"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "be0fd8b9cd9f8a94428ea8ac5ec84f4f7bab23697236b7a2e54d8537834e0315"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "8f554f10f3ca26505c1f51871263a7d75fca1e07a288c60c1a96b18f830beede"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "1aa7510ec1a3994273a20f8b341f676583b9ede2eaea3badd46deb7178d92a6c"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "17dc4f0920a4089790c8d13abff319a5e83f2aea7a06cdd3cc79699fa5ccdc8a"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "d44a47592608a2ef6eb105eb6a4642839e1a9ea59736b92345c0fa492ddbc47a"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "02afa656e08ce408c1b541e60d9126b8bac35b55a26950547291ee8f54c1899d"
metafile = true

[[files]]
file = "mods/qkl.pw.toml"
hash = "78fe291bc3d50234209d5b80735b469044f4d858dc8d3ba5bc38d1e098cb786f"
metafile = true

[[files]]
file = "mods/qsl.pw.toml"
hash = "f2b64534ac741a2a5f4ea7aa59585e1a5e60160e65cddac301d3cf46eb335150"
metafile = true

[[files]]
file = "mods/quilt-loading-screen.pw.toml"
hash = "77aa1af076bfb1175a407037a2d1db80437bae5193db45a557f5f32b3cc4a67f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "b2e3be698473bfb3f08865a11e74c9ee8d47239ac72a79d60acc1ee381722a50"
metafile = true

[[files]]
file = "mods/smoothboot-fabric.pw.toml"
hash = "971e8b0bef16bd6ce88c7f940b30fdc1debff7b715058f4d331d54beb58a4314"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "8da0d4c285e7e57aee3f08ab4e268d04518704ace4060744f042aef3a7f6bc50"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "aa4dcf55ac3191b0b31437521714c1d28364c3396cf06ef07fa76a08488c1837"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "08d9f157fea976ba8e7a20ebfce995fe5419ebddf581fcdab079aaceb33053e3"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "2aeab4f3b0a720ed02f400d9b521f1858474d4f8f7c3577ce916d5aa31fe37e1"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "ff9734e83519d4b1a516101f16b30650d00877d55ac1b62c24466ee2cc2a825a"
metafile = true

[[files]]
file = "mods/the-twilight-forest.pw.toml"
hash = "881b98b88ed5bd166490dad31e1f48f132e755ea0f8aacb61e67003dd6e551bc"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
hash = "4f782435d758d3cfd57ba49e2a4994006722d42307ef74ef3d35a1704f9ed5c4"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "1a3eab9fd9cdc70f36dd1dff01a48a6cb5113cf3482861646db3262bba99e27d"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "4a781874847eb651d839e150d3e0429f81b7ff5462065ace6679a2e193340b01"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "80bab11e8d1438ec93695050f087dc2f9d0ae1d2523a17b8236af7029f14119e"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "df9929f0a90f0c54a870ed182c0543ce579d07b84089d2fec6131917c53b5bab"
metafile = true
